version: '3.0'

services:

    web:
        container_name: nginx
        image: nginx
        volumes:
            - ./admin.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8080:80"
        environment:
            #- NGINX_HOST=foobar.com
            - NGINX_PORT=80
        command: /bin/bash -c "exec nginx -g 'daemon off;'"
